### PR TITLE
[Frontend]: fix responsiveness of brand login & signup

### LINKED ISSUE #24: [Frontend] Make BrandRegistrationForm  Responsive
## Description

- [ ]  It should work for all the screen sizes and should be properly alligned 

| Page Name                          | Description                                                   | Assignee       |
|------------------------------------|---------------------------------------------------------------|----------------|
| BrandRegistrationForm.js                   | Form for brand registration                            |                |

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
closes #24 
Screenshot 2024-06-17 at 18 03 54

As stated in previous PR, I was able to achieve responsiveness #41

### CODE REVIEW

**Comment by RohitGupta1237** [comment]
@Vidip-Ghosh  the arrows used for back button is not aligned it should be on left side of bar its coming in middle and border of boxes outside color is purple not getting compatible with other color designs else u make it same like its for login field to have consistency

**Comment by RohitGupta1237** [comment]
@Vidip-Ghosh attaching ss 
Screenshot 2024-06-17 at 6 57 36 PM

**Comment by RohitGupta1237** [comment]
@Vidip-Ghosh no no remove that purple border that surrounds the box

**Comment by RohitGupta1237** [comment]
@Vidip-Ghosh also that arrow above create account heading

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh and remove that purple border that surrounds the box make it similar to login boxes

This is done but unable to make the arrow to the left.

**Comment by RohitGupta1237** [comment]
@Vidip-Ghosh  hey its still showing that purple color when u click the box  and its showing 2 backgorund colors 
Screenshot 2024-06-17 at 8 23 28 PM

**Comment by Vidip-Ghosh** [comment]
Screenshot 2024-06-17 at 20 38 @RohitGupta1237  src=
@RohitGupta1237 is this okay?

**Comment by Vidip-Ghosh** [comment]
> > @Vidip-Ghosh and remove that purple border that surrounds the box make it similar to login boxes
> 
> This is done but unable to make the arrow to the left.

Wait let me push the code.

**Comment by Vidip-Ghosh** [comment]
Now let me know the final changes which needs to be done.

**Comment by RohitGupta1237** [comment]
@Vidip-Ghosh  can we connect on meet for 5 min ?

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh can we connect on meet for 5 min ?

9:30 would be okay? I need to take dinner.

**Comment by RohitGupta1237** [comment]
@Vidip-Ghosh  ya its okay ..we can connect at 9:30

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh ya its okay ..we can connect at 9:30

Please send meet link.

**Comment by RohitGupta1237** [comment]
@Vidip-Ghosh  https://meet.google.com/gpg-cosm-jvj

**Pull request closed without merging**
