### PR TITLE
fixes: issue#24 brand register form responsive

### LINKED ISSUE #24: [Frontend] Make BrandRegistrationForm  Responsive
## Description

- [ ]  It should work for all the screen sizes and should be properly alligned 

| Page Name                          | Description                                                   | Assignee       |
|------------------------------------|---------------------------------------------------------------|----------------|
| BrandRegistrationForm.js                   | Form for brand registration                            |                |

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
closes #24 

https://github.com/Kajol-Kumari/InfluMart/assets/91741581/0a93879c-b7bd-4c02-905a-7ff08ac60496

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Screenshot 2024-06-12 at 5 42 04 PM

- [ ] The text box on click of field doesn't look clean, it should align with the shape of the text box.
- [ ] The icons respective of the inbox boxes needs to be revised so that it make meaningful sense
- [ ] The Login Page responsiveness I am looking for as well

**Comment by Vidip-Ghosh** [comment]
> * [ ]  The icons respective of the inbox boxes needs to be revised so that it make meaningful sense

Okay I'll look into it.

**Comment by RohitGupta1237** [comment]
@Vidip-Ghosh  hey any doubt with this task?

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh hey any doubt with this task?

@RohitGupta1237 I guess someone already solved the issue. 
When I synchronized my forked repo & took a pull of changes in local, then I found that the changes which I was supposed to do is already there.

**Comment by RohitGupta1237** [comment]
@Vidip-Ghosh  the page is just integrated with backend its not responsive though like its adjusting with screen size so u can fix that in this

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh the page is just integrated with backend its not responsive though like its not adjusting with screen size so u can fix that in this

Sure, I will look into it.

**Comment by Vidip-Ghosh** [comment]
@RohitGupta1237 please review #41

**Pull request closed without merging**
