### PR TITLE
Created CollabPost page similar to figma design.

### PR DESCRIPTION
**Pull request by siddharthisrani**
Implemented the CollabPost page based on the provided Figma design.
Ensured the layout is responsive across various screen sizes.
Applied consistent styling to match the Figma design, including colors, padding, and font sizes.
Used react-native-vector-icons for icons in the search bar and footer navigation.
Ensured clean, readable, and maintainable code with TouchableOpacity for clickable elements.

### CODE REVIEW

**Comment by RohitGupta1237** [comment]
@siddharthisrani  can we connect on meet for 5 min?

**Comment by siddharthisrani** [comment]
@RohitGupta1237  Yeah, sure... It's a pleasure to contribute more and work on this project

Screen recording Drive link :- https://drive.google.com/file/d/1MtHQSGmBcWCZL10q75f8Vc9oGZ-OSm0E/view?usp=drivesdk

**Comment by RohitGupta1237** [comment]
@siddharthisrani  https://meet.google.com/bzo-hdgg-dwy. if u can join this meet

**Comment by siddharthisrani** [comment]
@RohitGupta1237 Actually i not in good network right now using mobile network. Hope you understand

**Comment by RohitGupta1237** [comment]
@siddharthisrani  ya no issues come checks are failing if u can fix them and will create more issues like this if u work on them

**Comment by RohitGupta1237** [comment]
@siddharthisrani 

collab post code 
 https://drive.google.com/drive/folders/1EckmkDR7I9eXL49z1Ix9zDk0W5jkfAbb?usp=sharing

campaign detail page 
https://drive.google.com/drive/folders/14UTdwPxppVUlQDh8SeHlA0hRAnnO3lwd?usp=sharing

collab form 

https://drive.google.com/drive/folders/1T0kybHldttZxVGEMmMIZ-NK0caMj8rVB?usp=sharing

**Comment by RohitGupta1237** [comment]
@siddharthisrani  if u can add a screen recording also

**Comment by siddharthisrani** [comment]
@RohitGupta1237 It was the CollabPost code that I had shared in the screen recording with the Drive link. Please provide the Figma designs for the Campaign Details Page and the Collab Form. I am going to work on them and would appreciate your feedback.

**Comment by RohitGupta1237** [comment]
@siddharthisrani  https://www.figma.com/design/B0vUURYrBFJGg8j8CNoLqn/designs?node-id=766-175&t=qJg6e2crojriVa8D-1

**Comment by siddharthisrani** [comment]
Screen Recording Drive link of CampaignDetail and CollabForm :- https://drive.google.com/file/d/1eRBVKqbr25T3LdU0IfclQml8R98Jqa43/view?usp=sharing

**Comment by RohitGupta1237** [comment]
@siddharthisrani  hey can u take latest pull and raise pr again

**Comment by siddharthisrani** [comment]
@RohitGupta1237 yes i have pull the latest ,After pull ..In App.js there is only import left of all my three components and in <Stack.screen> they got vanished which i added so should i add that again and then raise the pr or is it ok?

**Comment by RohitGupta1237** [comment]
yes raise the pr again if possible

**Comment by siddharthisrani** [comment]
@RohitGupta1237 Yes raised with updation .

**Comment by siddharthisrani** [comment]
@RohitGupta1237 What happened? any update on merging the code?

**Comment by siddharthisrani** [comment]
Hii @RohitGupta1237 Any update on my PR? It was not merged and issue is closed?

**Comment by RohitGupta1237** [comment]
@siddharthisrani  Hey there is slight change in plan so that issue we won’t be taking for now for u we can create a simple colour fix issue and make it level 3 to save ur time and efforts if u r ok with this ..

**Comment by siddharthisrani** [comment]
@RohitGupta1237 Yes i am ok with it

**Comment by RohitGupta1237** [comment]
@siddharthisrani  hey issue created

**Pull request closed without merging**
