### PR TITLE
Fixed responsiveness and interactivity in HomePage and influencer registration form

### LINKED ISSUE #26: [Frontend] Make HomePage and InfluencerRegistrationForm pages Responsive
## Description
Currently the frontend components are coded in ReactiveNative as per the figma designs but these are not responsive when run so making them responsive is required. in influencer registration form when someone clicks + to enter their social media handle then a popup input should appear to enter the handle and and verify button and when user clicks price '->' sign  then again a popup to enter input value and a dropdown for choosing location and industry assosciaiton should be a a input field while others boxes are tickables like age .The bottom bar and menu bar  should be fixed and should not be scrollable while the other part of page should be scrollable.

- [ ]  It should work for all the screen sizes.

| Page Name                          | Description                                                   | Assignee       |
|------------------------------------|---------------------------------------------------------------|----------------|
| Homepage.js                        | Main homepage of the application                               |                |          |
| InfluencerRegistrationForm.js      | Form for influencer registration                               |                |

### PR DESCRIPTION
**Pull request by shivamgaur99**
fixes #26 

## Tasks:

1. Homepage:

- Implement responsive design to ensure compatibility with various screen sizes and orientations.
-  Ensured the bottom bar and menu bar remain fixed and visible while enabling scrollability for the rest of the page content, improving navigation and user experience.

2. Influencer Registration Form:

- Implement responsive design to ensure compatibility with various screen sizes and orientations.
- Adapted the form layout to different screen sizes and orientations to ensure consistent usability across devices.
- Introduced pop-up input dialogs for seamless entry of social media handles and pricing details, enhancing user interaction and ease of use.
- Added dropdown menus within pop-up dialogs for selecting location and industry association, facilitating accurate data entry and customization.
- Enabled toggle functionality for age selection checkboxes, simplifying user input and improving accessibility.

### CODE REVIEW

**Comment by shivamgaur99** [comment]
@Kajol-Kumari @RohitGupta1237 please review everything as expected or not and let me know if any chnages required
Your feedback on any further adjustments needed would be greatly appreciated before finalizing the pull request.

**additional note:** This is an intermediate update, not the final pull request.

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@shivamgaur99 the ui looks distorted, please use the deploy preview url to check the same - https://deploy-preview-68--influmart.netlify.app/

**Comment by shivamgaur99** [comment]
@Kajol-Kumari @RohitGupta1237 could you please check changes

**Comment by Kajol-Kumari** [comment]
@shivamgaur99 please resolve the conflict in the pr

**Comment by shivamgaur99** [comment]
@Kajol-Kumari is responsiveness part okay ? like homepage..

**Pull request closed without merging**
