### PR TITLE
BrandAccountSignupDataPreview Page made as Responsive

### PR DESCRIPTION
**Pull request by BHS-Harish**
**Issue #58 Fixed**

 - [x] Profile page upload option added.

### CODE REVIEW

**Comment by BHS-Harish** [comment]
Hello @RohitGupta1237 

Review my changes.

**Comment by RohitGupta1237** [comment]
@BHS-Harish  hey check mail shared figma ..change color of remove image instead of red make it same as shared in figma upload new photo button red looks odd and other issue is that there are 2 background color when u cchange screen size fix that and put a default photo instaed of free empty space if someone wants to add phot its fine else show a default image else alignment is fine 

attaching ss
Screenshot 2024-06-19 at 10 57 29 PM

**Comment by BHS-Harish** [comment]
I displayed default images but it not shown. But it's visible once you remove the photo.

**Comment by RohitGupta1237** [comment]
@BHS-Harish  okay get  other issues then  fixed pls

**Comment by BHS-Harish** [comment]
Hey @RohitGupta1237 

All are fixed.. please check it.

**Comment by RohitGupta1237** [comment]
@BHS-Harish  perfect!!

**Pull request merged**
