### PR TITLE
[Frontend]: Fix brand register page

### LINKED ISSUE #24: [Frontend] Make BrandRegistrationForm  Responsive
## Description

- [ ]  It should work for all the screen sizes and should be properly alligned 

| Page Name                          | Description                                                   | Assignee       |
|------------------------------------|---------------------------------------------------------------|----------------|
| BrandRegistrationForm.js                   | Form for brand registration                            |                |

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
Closes #24 
### **Before:**
Screenshot 2024-06-15 at 14 48 59
Screenshot 2024-06-15 at 15 04 20

I've debugged by changing color which made it easier to identify the bug.

### **After:**
Screenshot 2024-06-15 at 14 57 16
Screenshot 2024-06-15 at 15 00 38

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@Vidip-Ghosh couple of things here:

-  The signUp Form should take the whole screen as are targetting the UI only for the app rn so it should adjust the mobile's screen. For web, we will do later ref ss - 
Screenshot 2024-06-15 at 4 11 15 PM

- This issue Should have covered the LoginPage Responsiveness as well but as its already done, can u please enhance its look like adding blue color boundry round the input box

Screenshot 2024-06-15 at 4 14 29 PM

- Revert the deleted sign/login files and do the changes on the top of current code, There is a lot of un-necessary changes in this pr.

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh couple of things here:
> 
> * The signUp Form should take the whole screen as are targetting the UI only for the app rn so it should adjust the mobile's screen. For web, we will do later ref ss -
> 
> Screenshot 2024-06-15 at 4 11 15 PM
> * This issue Should have covered the LoginPage Responsiveness as well but as its already done, can u please enhance its look like adding blue color boundry round the input box
> 
> Screenshot 2024-06-15 at 4 14 29 PM
> * Revert the deleted sign/login files and do the changes on the top of current code, There is a lot of un-necessary changes in this pr.

Okay I will look into it. But can you please explain the first point what I have to do?

**Comment by Kajol-Kumari** [comment]
@Vidip-Ghosh This is how the page looks for a little large screen after you change, it should ideally strech to available length and width just like the signIn page example screenshot i shared you above
Screenshot 2024-06-15 at 5 42 31 PM

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh This is how the page looks for a little large screen after you change, it should ideally strech to available length and width just like the signIn page example screenshot i shared you above Screenshot 2024-06-15 at 5 42 31 PM

Okay I got it.

**Comment by RohitGupta1237** [comment]
@Vidip-Ghosh  any doubts with this ?

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh any doubts with this ?

Codebase seems to be messed up in my local.
I will try to fix else will create a new branch & raise a PR.

**Comment by RohitGupta1237** [comment]
@Vidip-Ghosh  its ok if u create a new branch and raise a pr

**Comment by RohitGupta1237** [comment]
@Vidip-Ghosh  are u still working on this issue ?

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh are u still working on this issue ?

Yes

**Pull request closed without merging**
