### PR TITLE
Added "Community Chat"[frontend + backend]

### LINKED ISSUE #197: Feature: Add the community chat support[both frontend + backend]
Add the community chat support[both frontend + backend]

### PR DESCRIPTION
**Pull request by arunimaChintu**
This setup will enable a basic community chat feature for InfluMart. The frontend connects to the backend via Socket.io to send and receive messages in real-time.
Closes #197

### CODE REVIEW

**Comment by RohitGupta1237** [comment]
@arunimaChintu its failing checks can u add screen recroding pls with this

**Comment by arunimaChintu** [comment]
@RohitGupta1237 Okay! I will look into it...

**Comment by arunimaChintu** [comment]
@Kajol-Kumari corrected the failing checks...

**Comment by arunimaChintu** [comment]
@Kajol-Kumari you can merge it now...

**Comment by RohitGupta1237** [comment]
@arunimaChintu  hey can u add a screen recording of this pls

**Pull request closed without merging**
