### PR TITLE
FailedPaymentStatus and AccountCreatedSuccessfullyNoti pages made as Responsive

### PR DESCRIPTION
**Pull request by BHS-Harish**
**Issue #25 Fixed**

**Screenshot**
Screenshot 2024-06-24 220448
Screenshot 2024-06-24 220506
Screenshot 2024-06-24 220557

### CODE REVIEW

**Comment by BHS-Harish** [comment]
Hey @RohitGupta1237 

Please review the request

**Comment by RohitGupta1237** [comment]
@BHS-Harish 
Screenshot 2024-06-24 at 10 16 19 PM

hey its still showing together in bottom bar

**Comment by BHS-Harish** [comment]
wait.. let me check it

**Comment by BHS-Harish** [comment]
@RohitGupta1237 

Now it's fine

**Pull request merged**
