### PR TITLE
HomePage.js made as responsive

### PR DESCRIPTION
**Pull request by BHS-Harish**
**Issue #76 Fixed**

### CODE REVIEW

**Comment by BHS-Harish** [comment]
Hey @RohitGupta1237 

Please review my request.

**Comment by RohitGupta1237** [comment]
@BHS-Harish  checking

**Comment by RohitGupta1237** [comment]
@BHS-Harish  is the images uses is fixed dimesnion or its getting adjusted with screen layout like when screen size changes its getting cut .

**Comment by BHS-Harish** [comment]
The height was fixed width will took the entire width automatically

**Comment by RohitGupta1237** [comment]
@BHS-Harish  but it will cut image then whenever screen size changes then

**Comment by RohitGupta1237** [comment]
@BHS-Harish  
Screenshot 2024-06-23 at 11 59 58 PM

secondly why this much white space is coming  between contents and bottom bar

**Comment by BHS-Harish** [comment]
@RohitGupta1237  The image will overflow if we use fixed width and height for image for small devices.

**Comment by RohitGupta1237** [comment]
and why too much empty space is coming

**Comment by BHS-Harish** [comment]
> and why too much empty space is coming between bottom bar and content

@RohitGupta1237  Because it set as fixed at bottom so we can't avoid that whitespace.

**Comment by RohitGupta1237** [comment]
@BHS-Harish  rest is perfect

**Comment by RohitGupta1237** [comment]
@BHS-Harish  is there any way that photo adjusts and it doesnot get cut too

**Comment by BHS-Harish** [comment]
@RohitGupta1237 

If we adjust the photo cut issue, then the image size will affected
If we set the images size suitable for all devices, then the photo will cut.

So we can't to do both the things at same time

**Comment by RohitGupta1237** [comment]
@BHS-Harish  ok

**Comment by BHS-Harish** [comment]
@RohitGupta1237  Ok... Anything else..?

**Comment by RohitGupta1237** [comment]
@BHS-Harish  rest is fine

**Pull request merged**
