### PR TITLE
BrandOrInfluencer and OtpVerification page made as responsive

### PR DESCRIPTION
**Pull request by BHS-Harish**
**Issue #56**

**Screenshot**
OTP Verification
image

BrandOrInfluencer
image

### CODE REVIEW

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari  @RohitGupta1237 

Please review the changes.

**Comment by RohitGupta1237** [comment]
@BHS-Harish  hey in otp verification when zooming screen buttons are overlapping not adjusting with screen layout like when zoom in to much they should align vertically but then overlap 

in brand or influencer add scrolling as when zooming in its not scrollign down that it should have been 

attaching ss
Screenshot 2024-06-18 at 11 56 06 PM
Screenshot 2024-06-18 at 11 55 51 PM
Screenshot 2024-06-18 at 11 56 40 PM

**Comment by BHS-Harish** [comment]
Okay @RohitGupta1237 

Let me fix it

**Comment by BHS-Harish** [comment]
**Fixed**

image

image

**Pull request merged**
