### PR TITLE
Done in making responsive of chatinteface and inboxinterface

### PR DESCRIPTION
**Pull request by TheNikhilRaj**
[Frontend] Make the ChatInterface Responsive #20
DONE!
@Kajol-Kumari

### CODE REVIEW

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj Hey making inbox box interface responsive  is also included in this.

**Comment by TheNikhilRaj** [comment]
> @TheNikhilRaj Hey 1.making inbox box interface responsive is also included in this. 2.The color scheme is not exactly the same as it shown in figma design 3. Alignment of icons is little deviated
> 
> attaching ss from expected and what it is appearing now IMG_0024 Screenshot 2024-06-13 at 3 25 19 PM

@RohitGupta1237 okay then assign me this task seperately because one i have already done the chatinterface keep seperate both.

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj  ya definitely i will do that .. before if you can fix the suggestions mentioned in chat interface.

**Comment by TheNikhilRaj** [comment]
@RohitGupta1237 okay then assign me this task seperately because one i have already done the chatinterface keep seperate both. 

In figma this design mentioned and you saying work on different design??
339313863-c7af6495-3369-444e-901a-5b954d5452a8
i have work on this or different??
@RohitGupta1237

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj  can we connect on a short meet ? now

**Comment by TheNikhilRaj** [comment]
> @TheNikhilRaj can we connect on a short meet ? now

okay @RohitGupta1237

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj  https://meet.google.com/zwz-sxzo-wiz

**Comment by TheNikhilRaj** [comment]
@RohitGupta1237 @Kajol-Kumari  Please keep seperate the chatinterface and inboxinterface.

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj  i have created them separately ...

**Pull request closed without merging**
