### PR TITLE
Fixed Responsiveness of HomePage.js and InfluencerRegistrationForm.js

### LINKED ISSUE #26: [Frontend] Make HomePage and InfluencerRegistrationForm pages Responsive
## Description
Currently the frontend components are coded in ReactiveNative as per the figma designs but these are not responsive when run so making them responsive is required. in influencer registration form when someone clicks + to enter their social media handle then a popup input should appear to enter the handle and and verify button and when user clicks price '->' sign  then again a popup to enter input value and a dropdown for choosing location and industry assosciaiton should be a a input field while others boxes are tickables like age .The bottom bar and menu bar  should be fixed and should not be scrollable while the other part of page should be scrollable.

- [ ]  It should work for all the screen sizes.

| Page Name                          | Description                                                   | Assignee       |
|------------------------------------|---------------------------------------------------------------|----------------|
| Homepage.js                        | Main homepage of the application                               |                |          |
| InfluencerRegistrationForm.js      | Form for influencer registration                               |                |

### PR DESCRIPTION
**Pull request by shivamgaur99**
closes #26 

Fixed Responsiveness of HomePage.js and InfluencerRegistrationForm.js
added dropdown and eye icon for password visibility

image

### CODE REVIEW

**Comment by shivamgaur99** [comment]
@Kajol-Kumari @RohitGupta1237  both pages are responsive please check

**Comment by RohitGupta1237** [comment]
@shivamgaur99  hey the alignment is not getting upto mark attaching ss for refernece 
Screenshot 2024-06-23 at 11 30 23 PM

**Comment by shivamgaur99** [comment]
@RohitGupta1237 but here it showing good
image

**Comment by RohitGupta1237** [comment]
@shivamgaur99  but for different screen size its not proportional

**Comment by shivamgaur99** [comment]
okay i am fixing it

**Comment by RohitGupta1237** [comment]
@shivamgaur99  for other screen size also its overflowing 
Screenshot 2024-06-23 at 11 41 48 PM

**Comment by shivamgaur99** [comment]
@RohitGupta1237 we are using different different component in home page may be this is reason because after refresh it showing good, but i will try to fix it 
image
image

**Pull request closed without merging**
