### PR TITLE
Added API for keeping track of collaborations

### LINKED ISSUE #49: [Backend] A api to keep track of collaborations between brands and influencers
- [ ] API to keep record of no of collaborations done by brands on the portal and  keeping the record of all the collaborations done by brand which includes whats the average growth value of followers , post frequency which means no of posts they post in a month , whats average engagement rate they look that comes after analysing all the deals brand made with influencers ...that they look for dealing with influencer. 

- [ ] API to track record of minimum followers brand look in influencer. , average minimum likes and post frequency...in above api we track all collaborations and analyse them and then show insights whereas in this only we will look for minimum requirements which is usually the lowest data of all collaboration the brand had dealed with influencer.

for better reference look brand profile page in updated sample video

### PR DESCRIPTION
**Pull request by Asymtode712**
## Description

Fixes #49 
- Created a new collaboration model in `model/collaboration.js`
- Created controllers for collaborations in `controllers/collaborationController.js` that contains functions for creating and retrieving collaborations, getting the minimum requirements and fetching collaboration analytics
- Created API routes associated to collaborations in `routes/collaborationRoutes.js`

## Note to maintainers

@RohitGupta1237 @Kajol-Kumari Please check this PR and suggest any changes if required

P.S: I have made the `model/collaboration.js` considering the models related to brand and influencer, so if you think that some changes are required then please specify them

### CODE REVIEW

**Comment by Asymtode712** [comment]
@RohitGupta1237 @Kajol-Kumari Please review this PR and convey any changes if they are to be made

**Comment by RohitGupta1237** [comment]
@Asymtode712  hey can we connect on meet for 5 min now if possible?

**Comment by Asymtode712** [comment]
@RohitGupta1237 Yes sure

**Comment by RohitGupta1237** [comment]
@Asymtode712  https://meet.google.com/bwg-mhcn-bhy

**Comment by Asymtode712** [comment]
@RohitGupta1237 Please check this testing video:


https://github.com/Kajol-Kumari/InfluMart/assets/115717746/ad6d3233-342e-4fa1-8d3c-e40bd21fa546

**Comment by Asymtode712** [comment]
@RohitGupta1237 In the above testing, I have created 2 influencers' collab with different attributes so as to vary the minimum-requirements and analytics

**Comment by RohitGupta1237** [comment]
@Asymtode712  hey collaboration all endpoints are accessible to all so add a auth middleware pls.

**Comment by Asymtode712** [comment]
@RohitGupta1237 Sure, anything else??

**Comment by RohitGupta1237** [comment]
@Asymtode712  rest seems fine

**Comment by Asymtode712** [comment]
@RohitGupta1237 Have added the auth middleware

**Comment by Asymtode712** [comment]
@RohitGupta1237 Please add relevant labels and assign me this PR

Thank you!

**Pull request merged**
