### PR TITLE
InfluencerRegistrationForm and related pages made as responsive

### PR DESCRIPTION
**Pull request by BHS-Harish**
**Issue #79  Fixed**

**Following Pages made as responsive**
- [x] InfluencerRegistrationForm.js
- [x] AddHandles.js
- [x] MaxFollowersNo.js
- [x] PricePerPost.js
- [x] UserProfilePhoto.js

### CODE REVIEW

**Comment by BHS-Harish** [comment]
@RohitGupta1237 

Please review the request.

**Comment by RohitGupta1237** [comment]
@BHS-Harish  
Screenshot 2024-06-25 at 12 12 39 AM


profile photo text is not aligned properly

**Comment by BHS-Harish** [comment]
ok let me change it.

**Comment by BHS-Harish** [comment]
@RohitGupta1237 

Now...It's fine...

**Pull request merged**
