### PR TITLE
[Frontend] Making inbox interface responsive. #36

### PR DESCRIPTION
**Pull request by TheNikhilRaj**
Closes: #36 
Done, Made changes in inbox interface responsive. #36
Capture
#36

### CODE REVIEW

**Comment by TheNikhilRaj** [comment]
@RohitGupta1237 i am facing error while generating the PR.

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj  why?

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj if possible upload screen recording video

**Comment by TheNikhilRaj** [comment]
> @TheNikhilRaj if possible upload screen recording video

can we have meet?

**Comment by RohitGupta1237** [comment]
yes sure https://meet.google.com/ays-tcow-svw

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj  https://meet.google.com/ays-tcow-svw

**Comment by TheNikhilRaj** [comment]
Hey i have done the changes it gives error as same as yesterday!
Capture1
@RohitGupta1237

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj  the + sign should be on right corner ..its coming in middle of page

**Comment by TheNikhilRaj** [comment]
> @TheNikhilRaj the + sign should be on right corner ..its coming in middle of page

Capture2
@RohitGupta1237 Done!

**Comment by TheNikhilRaj** [comment]
Hello @RohitGupta1237 ?

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj  yes tell

**Comment by TheNikhilRaj** [comment]
> @TheNikhilRaj yes tell

Capture2
changes done! @RohitGupta1237

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj  hey ya ui is looking fine , kajal mam will give a final thumbs up.

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@TheNikhilRaj seems like u deleted the file but didn’t remove its usages which is breaking the build, please remove the references if the file isn’t required anymore -

`Error: Unable to resolve module ./screens/ChatInterface from /opt/build/repo/frontend/App.js: `

**Comment by TheNikhilRaj** [comment]
> @TheNikhilRaj seems like u deleted the file but didn’t remove its usages which is breaking the build, please remove the references if the file isn’t required anymore -
> 
> `Error: Unable to resolve module ./screens/ChatInterface from /opt/build/repo/frontend/App.js: `

@Kajol-Kumari but currently i have only 1 task done "Inbox Interface" so what should i do for Inbox Interface.
@RohitGupta1237

**Comment by Kajol-Kumari** [comment]
@TheNikhilRaj then u have mistakenly deleted the chatInterfaceFile, either revert the deletion or raise a new pr with just inbox changes

**Comment by TheNikhilRaj** [comment]
@Kajol-Kumari Please give me the acces to push my changes.

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@TheNikhilRaj the changes looks good, need final refactoring before merge. Please create a folder lets say `chat`/`communicate` under `screens` and then add these 2 files and their css file inside the same, please make sure to move all the styles defined within these 2 files to their respective css files. Reference - https://github.com/Kajol-Kumari/InfluMart/tree/main/frontend/screens/signup

**Comment by TheNikhilRaj** [comment]
> @TheNikhilRaj the changes looks good, need final refactoring before merge. Please a folder lets say `chat`/`communicate` and then add these 2 files and their css file inside the same, please make sure to move all the styles defined within these 2 files to their respective css files. Reference - https://github.com/Kajol-Kumari/InfluMart/tree/main/frontend/screens/signup

@Kajol-Kumari I have add the InboxInterface file into the given reference folder?

**Comment by Kajol-Kumari** [comment]
@TheNikhilRaj I don't get u, what's the confusion, i am asking u to put those 2 files along with the seggregated css file in a new folder that's it no?

**Comment by TheNikhilRaj** [comment]
> @TheNikhilRaj I don't get u, what's the confusion, i am asking u to put those 2 files along with the seggregated css file in a new folder that's it no, just like all the other contributors are doing after fixing the responsiveness

@Kajol-Kumari No i had putted the file in that same "screen" folder.

**Comment by Kajol-Kumari** [comment]
@TheNikhilRaj Please read my comment properly. All I was asking for refactoring, which i have done myself now :)

**Pull request merged**
