### PR TITLE
ui changes #270

### PR DESCRIPTION
**Pull request by siddharthisrani**
Changes Made
Updated the color of the "Login Successful" notification button to match the standard blue color used for other buttons in the application.

### CODE REVIEW

**Comment by RohitGupta1237** [comment]
@siddharthisrani  u have to just change background color not this much only colour code in this

**Comment by siddharthisrani** [comment]
@RohitGupta1237 Yes it was the code that i worked before i didnt deleted the Repo or created new Fork i just updated the changes and made new branch and added only that file i have chnaged. Should i have to delete the repo and make new fork?

**Comment by Kajol-Kumari** [comment]
> @RohitGupta1237 Yes it was the code that i worked before i didnt deleted the Repo or created new Fork i just updated the changes and made new branch and added only that file i have chnaged. Should i have to delete the repo and make new fork?

@siddharthisrani  make sure to follow - 
```
# Add the remote, call it "upstream":

git remote add upstream https://github.com/Kajol-Kumari/InfluMart

# Fetch all the branches of that remote into remote-tracking branches

git fetch upstream

# Make sure that you're on your main branch:

git checkout main

# Rewrite your main branch so that any commits of yours that
# aren't already in upstream/main are replayed on top of that
# other branch:

git rebase upstream/main
```

FYI - https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github

**Comment by siddharthisrani** [comment]
Thanks @Kajol-Kumari I've opened a new pull request to update the button color of the login successful notification.
Please review the changes and provide any feedback you may have. Thank you!

**Comment by Kajol-Kumari** [comment]
> Thanks @Kajol-Kumari I've opened a new pull request to update the button color of the login successful notification. Please review the changes and provide any feedback you may have. Thank you!

@siddharthisrani check the file change in this pr, you have messed up while pulling the latest commit from master, the review is useless unless you clean the pr and have only required changes :)

**Pull request closed without merging**
